### ISSUE TITLE
Move CLI to another repository

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/ImageGoNord#110]
I'm sorry for all, but as a matter of order we have to move the cli to another repository

**Comment by FObersteiner** [comment]
> I'm sorry for all, but as a matter of order we have to move the cli to another repository

so, does this mean the CLI won't be available anymore in future versions of this repo?

**Comment by Wabri** [comment]
Simply the cli will not be in this repository, but there will be a repository called ign-cli or something like that. Will be a problem for you?

**Comment by FObersteiner** [comment]
hm no, don't think so, was just confused ;-) The nord style conversion is pretty cool and for occasional use I like the CLI. For heavy use, a Python script is better I guess.

The reason why I found this issue is that I thought there could be some minor tweaks, like a case-insensitive regex pattern for images (.jpg and .JPG shouldn't make a difference).

**Comment by TheJoin95** [comment]
Good point, that's why we are using our centralized pip library called image-go-nord, so it won't change anything and everything will be aligned :)

Thanks to point out this :)

**Comment by Wabri** [comment]
In process: https://github.com/Schrodinger-Hat/ImageGoNord-cli

**Comment by Artmorse** [comment]
The link seems to be dead ?
The other repository already exists ?

**Comment by Wabri** [comment]
@Artmorse is not dead is private for now in order to not expose secrets for the actions we are about to add to the new repository, as well as to make the first public appearance clean and tidy. Me and @BugliL are working on it, but you can open all the pr you want because the process will be long considering the scheduling on other projects as well.

**Comment by Wabri** [comment]
THE CLI IS MOVED HERE: https://github.com/Schrodinger-Hat/ImageGoNord-cli

Upcoming PR for cli features will be rejected on this repository and redirected to the new one.
