### ISSUE TITLE
Everforest

### ISSUE THREAD

**Issue by nksupermarket** [Schrodinger-Hat/ImageGoNord#131]
**Link to resources of the colors / palettes / projects / images**
[Everforest github](https://github.com/sainnhe/everforest)

**A comment or some key points in order to add this feature**
One of the most popular neovim themes. It looks great.

**Are there any correletion between you and the project / color / palette / image are you submitting?**
I use it.

**In which project: CLI, Web?**
Both

**Additional notes**
If enhancement is approved, please let me know how I should select colors eg. should I dump the entire theme into the json files or is there an ideal way to select colors?

**Comment by TheJoin95** [comment]
Thanks for the contributions, feel free to open a PR for that :)

**Comment by TheJoin95** [comment]
@nksupermarket are you up to contribute on this with a PR?

**Comment by TheJoin95** [comment]
Closing this per #160 
Thanks again to @JonathanBytes for the contribution 👯
