### ISSUE TITLE
Netlify preview failed

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/ImageGoNord#134]
**Describe the bug**
Netlify fail to create preview because:

```
7:18:26 PM: Browserslist: caniuse-lite is outdated. Please run:
7:18:26 PM: npx browserslist@latest --update-db
```

**To Reproduce**
1. Go to #127 
2. Click on netlify/jolly-leakey-e5f43b/deploy-preview details
3. Search for _caniuse-lite_

**Expected behavior**
Netlify provide the preview of the site

**Comment by TheJoin95** [comment]
Closing as old
