### ISSUE TITLE
Think about moving license mit -> something else

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/ImageGoNord#135]
Mit is too much permissive and our work need to be protected, but still open.

Other probable license:

- https://choosealicense.com/licenses/gpl-3.0/
- https://choosealicense.com/licenses/apache-2.0/

**Comment by TheJoin95** [comment]
Can I suggest https://choosealicense.com/licenses/agpl-3.0/ ?

**Comment by Wabri** [comment]
It seems ok!
