### ISSUE TITLE
Website front-end d

### ISSUE THREAD

**Issue by realitychemist** [Schrodinger-Hat/ImageGoNord#144]
(Accidentally posted while writing title – a hazard of opening issues on mobile – should read "Website front-end down")

The website front-end is down and returns what appears to be the text of a 403 FORBIDDEN response. Tested on OnePlus 8 running Android version 13, using Firefox mobile browser version 122.1.0.

1. Go to the website
2. Observe the bug

Returned text:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

**Comment by TheJoin95** [comment]
Thanks, it seems an SSL issue, we are going to fix that soon

**Comment by TheJoin95** [comment]
Fixed

**Comment by TheJoin95** [comment]
Need to re-open this as we are experiencing issue with ovh & netlify DNS. Need to investigate a bit better

**Comment by TheJoin95** [comment]
I'm migrating the DNS from ovh to netlify.
Need to monitor if we're receiving correctly the email in our inbox using the @schrodinger-hat.it domain addresses cc @Wabri

**Comment by TheJoin95** [comment]
Solved as we've updated the DNS
