### ISSUE TITLE
Automation publish on twitter

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/ImageGoNord#30]
Create new action to publish last images on sh twitter every 6 hours(?)

**Comment by Wabri** [comment]
I thought about this and I dont know if it worth the time. @TheJoin95 what do you think?

**Comment by TheJoin95** [comment]
We can try it on the SH account. It won't need that much of time.
We should create another Github Action that reads from our subreddit the new submission than post it onto our twitter feed, a couple of time per day.

I guess 4 post per day is the right amount, just for trying it.
If I can make it, I'll give it a try tonight. I'm gonna try to use nodejs and as a fallback python.

**Comment by TheJoin95** [comment]
I requested a twitter token API. It's gonna take some time to make it available, I guess.

**Comment by TheJoin95** [comment]
Twitter approved our submission to their API.
I added the API token, API secrets and token to the repo secrets

**Comment by Wabri** [comment]
Good

**Comment by TheJoin95** [comment]
Made it and merged it on the master branch.
I setted up the github action to run every 6h30m and it will publish just one tweet from our subreddit.

An example here: https://twitter.com/schrodinger_hat/status/1387189637463089155

Let's see how is gonna work and maybe let's discuss about which hashtag or profile tag we should put inside the status

**Comment by Wabri** [comment]
Ok, good. We'll see if it's worth it.
