### ISSUE TITLE
Site keeps loading

### ISSUE THREAD

**Issue by lajawi** [Schrodinger-Hat/ImageGoNord#36]
I tried converting an image on the [site](https://ign.schrodinger-hat.it/), but after a decent amount of time (already over 10 minutes) it is still loading.
- What am I doing wrong?
- Might the resolution be too high?

**Comment by TheJoin95** [comment]
Hi there, we were deploying a new version onto a new server.
There were some downtime on our API, I'm sorry for that.

Can you please try again now?

We are working to make the API and the website more accessible.
We are also working on make the documentation more clear to anyone in order to give to anyone the opportunity to try out the IGN algorithm.

Let me know, thank you for your feedback ;)

**Comment by lajawi** [comment]
> 
> 
> Hi there, we were deploying a new version onto a new server.
> There were some downtime on our API, I'm sorry for that.
> 
> Can you please try again now?
> 
> We are working to make the API and the website more accessible.
> We are also working on make the documentation more clear to anyone in order to give to anyone the opportunity to try out the IGN algorithm.
> 
> Let me know, thank you for your feedback ;)

It still doesn't work. Either it loads forever or doesn't change the palette. It worked one time, that's all.

**Comment by TheJoin95** [comment]
Can you trying again and take a screenshot of the demo area?
Try to clear also the cache of your browser or to navigate in an anonymous tab, in order to have the new files

**Comment by lajawi** [comment]
> 
> 
> Can you trying again and take a screenshot of the demo area?
> Try to clear also the cache of your browser or to navigate in an anonymous tab, in order to have the new files

I cleared all data from that site, using the addon Cookie Auto Delete, then I tried again.
As of the time of sending this, it is still loading:
![grafik](https://user-images.githubusercontent.com/51792807/114847348-e9285580-9ddd-11eb-8870-eb49dad25eb9.png)

**Comment by TheJoin95** [comment]
Ok, can you try to upload a different image in a lower resolution?
We put a 60s timeout per each job, in order to receive and process multiple request.

Can you write us also the details of your actual image? Size, resolution, ..

Thank you

**Comment by lajawi** [comment]
> 
> 
> Ok, can you try to upload a different image in a lower resolution?
> We put a 60s timeout per each job, in order to receive and process multiple request.
> 
> Can you write us also the details of your actual image? Size, resolution, ..
> 
> Thank you

The image seen above is 4035*2676 pixels, size 2,51MB, jpg

**Comment by TheJoin95** [comment]
Ok, can you please share it trough the issue uploader or imgur?
So we can test it out

**Comment by lajawi** [comment]
https://imgur.com/yFXcdGp

**Comment by TheJoin95** [comment]
I test it out and yes, it takes more than 60s.
I changed to a higher value now.

I retried and it worked, even with the filtering flag, the result:
![immagine](https://user-images.githubusercontent.com/6616203/114850113-b9c71800-9de0-11eb-9b72-5bb78199b89b.png)


Let me know if it's working also on your side

**Comment by lajawi** [comment]
> 
> 
> I test it out and yes, it takes more than 60s.
> I changed to a higher value now.
> 
> I retried and it worked, even with the filtering flag, the result:
> ![immagine](https://user-images.githubusercontent.com/6616203/114850113-b9c71800-9de0-11eb-9b72-5bb78199b89b.png)
> 
> Let me know if it's working also on your side

It did once
