### ISSUE TITLE
Website isn't working

### ISSUE THREAD

**Issue by McStecca** [Schrodinger-Hat/ImageGoNord#37]
I upload an image and it doesn't change. Any image i tried remained the same. It doesn't take time loading, there's like a second and then it stops

**Comment by TheJoin95** [comment]
Can you retry to upload and process the image?

We were uploading a new version of the algorithm on the API server.
We are using a little VPS on ovh.com

**Comment by TheJoin95** [comment]
We added an icon to check if the APIs are online or not :)
