### ISSUE TITLE
ImageGoNord website API is down

### ISSUE THREAD

**Issue by lokesh-krishna** [Schrodinger-Hat/ImageGoNord#54]
Been checking in intermittently for the last couple of weeks from multiple devices and browsers and the API always shows up as red for me and doesn't let me process images. Missing ImageGoNord terribly. 

**To Reproduce**
1. Go to [ImageGoNord](https://ign.schrodinger-hat.it/)
2. Check API status which is green
3. Click on 'Drop Image Here'
4. Click on Process
5. Watch as API status turns red

**Expected behavior**
You get a lovely Nord palette version of the image

**Screenshots**
![image](https://user-images.githubusercontent.com/20235646/124691370-5f2deb80-def9-11eb-9669-184815591d3c.png)

**Desktop:**
 - OS: Arch Linux
 - Browser Firefox 91, Qutebrowser 2.3

**Smartphone:**
 - Device: Redmi Note 7 Pro
 - OS: Android 11
 - Browser Firefox 91, Bromite 91

**Comment by Wabri** [comment]
We have some problem with the platform where we deploy the api and we work on it in the next days.

For now I recommend you to use the cli tool, is still in beta, but done the same job as the api and even better some times with large images.

Thanks for sharing this problem 🥇

**Comment by TheJoin95** [comment]
It was a Redis cache problem.
I clean up everything and restarted the service and now you should be able to upload and convert the image :)

Let us know!

**Comment by lokesh-krishna** [comment]
Working as fantastically as ever once again! Thank you so, so much!
