### ISSUE TITLE
[BUG] ImageGoNord Website Not Changing Images , Keeps on Loading

### ISSUE THREAD

**Issue by AsianCat54x** [Schrodinger-Hat/ImageGoNord#55]
I had a recent problem while processing my images with nord palette. The api status was green, yet the loader still loaded. I checked out console for some info and found the fetch fail error:

```
ign.schrodinger-hat.it/:1  Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by TheJoin95** [comment]
Thank you for reporting this issue.
Our redis was at its max memory capacity.

We just flush the unused memory, so everything restarted correctly.
You can try again on converting your images :)
