### ISSUE TITLE
 Add counter of converted images on ign site

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/ImageGoNord#70]

**Comment by TheJoin95** [comment]
Added in the latest release on the frontend website

**Comment by Wabri** [comment]
It is working?

<img width="389" alt="image" src="https://user-images.githubusercontent.com/12409541/156760264-881424d2-d216-4941-8e75-47867fd0a38b.png">

**Comment by TheJoin95** [comment]
ExCuS3 Me?!
![immagine](https://user-images.githubusercontent.com/6616203/156763734-e5dd3a5c-5cf6-4d37-8433-f2ff858a531f.png)

**Comment by Wabri** [comment]
Ahahahahahah now it's like that for me too
