### ISSUE TITLE
Can't find the Solarized palette.

### ISSUE THREAD

**Issue by GasparVardanyan** [Schrodinger-Hat/ImageGoNord#74]
Even **grep -R Solarized** and **find . | grep Solarized** don't show anything in the repo.
But there's a Solarized palette on the website: https://ign.schrodinger-hat.it/color-schemes

How to get that palette?

**Comment by Wabri** [comment]
Thanks to pointed this out, I will release in a few hours a new update with the solarized palette even for the cli!

**Comment by Wabri** [comment]
Hello @GasparVardanyan I update the cli palettes, you can find here https://github.com/Schrodinger-Hat/ImageGoNord/tree/master/src/palettes/Solarized
In order to use it you need to update your local repository!

**Comment by GasparVardanyan** [comment]
@Wabri thanks a lot!!
Sorry, but there are other palettes too on the website which don't appear in the repo ))

**Comment by Wabri** [comment]
ATM I dont have much time to add every palettes, but you can do it :smiley:

- Fork the repo, 
- Create directory under src/palettes with the name of the palette you want to add
- Create files with variant of the palette (for example https://github.com/Schrodinger-Hat/ImageGoNord/tree/master/src/palettes/Nord) or you can simply create a single file and put every hexadecimal color to it (like this https://github.com/Schrodinger-Hat/ImageGoNord/blob/master/src/palettes/Catppuccin/Night)
- Open a pull request https://github.com/Schrodinger-Hat/ImageGoNord/pulls and then I will merge :grin: 

Ask if you have any problem and thanks for the contributions

**Comment by GasparVardanyan** [comment]
@Wabri ok, I'll do it and do a pull request! Thanks for the reference!

**Comment by GasparVardanyan** [comment]
Is it ok to have same colors in multiple files in palette directory?

**Comment by Wabri** [comment]
If you add same colors in different files simply that color will be added 2 times, is not a problem!

Simply when remove a group of color from the palette that color will be stick if one of the group are added!

**Comment by Wabri** [comment]
I opened the issue #76 to keep track of your palette adding contribution :smile: 

We can keep discussing there :muscle:
