### ISSUE TITLE
More palettes to cli

### ISSUE THREAD

**Issue by Wabri** [Schrodinger-Hat/ImageGoNord#76]
As @GasparVardanyan pointed out in #74  there are not all palettes show in the site. 

Add more palettes to the cli is a good thing.

**Comment by GasparVardanyan** [comment]
I've created a pull request: #77

**Comment by Wabri** [comment]
Thank you @GasparVardanyan for this contribution 🥇

**Comment by GasparVardanyan** [comment]
Thank you all for this amazing project!
