### ISSUE TITLE
Add catppuccin theme to ImageGoNord

### ISSUE THREAD

**Issue by nightser727** [Schrodinger-Hat/ImageGoNord#86]
**Link to resources of the colors / palettes / projects / images**
repository [here]( https://github.com/catppuccin/catppuccin)
**A comment or some key points in order to add this feature**
Its a very nice looking color scheme and it would be very cool if it was available in the color palettes .

**Are there any correletion between you and the project / color / palette / image are you submitting?**
No i found it via discord 
**Additional notes**
No

**Comment by Wabri** [comment]
Hi @nightser727 thanks for the contribution.

Do you mean on the website? Because in the cli version there is alreaady the catppuccin theme: https://github.com/Schrodinger-Hat/ImageGoNord/tree/master/src/palettes/Catppuccin

**Comment by nightser727** [comment]
> Hi @nightser727 thanks for the contribution.
> 
> Do you mean on the website? Because in the cli version there is alreaady the catppuccin theme: https://github.com/Schrodinger-Hat/ImageGoNord/tree/master/src/palettes/Catppuccin

yes on the website

**Comment by Wabri** [comment]
@nightser727 now should be in the site 😃

**Comment by nightser727** [comment]
> @nightser727 now should be in the site 😃

Yea i checked it just after the issue was closed thanks.
